# frozen_string_literal: true

require "spec_helper"

RSpec.describe "generated setup note docs" do
  let(:generated_setup_note_path) do
    File.expand_path("../lib/generators/rails_fields_kit/templates/rails_fields_kit_setup.md", __dir__)
  end
  let(:generated_setup_note) { File.read(generated_setup_note_path) }

  it "keeps the generated setup note pointed at the maintained walkthrough without becoming a docs inventory" do
    expect(generated_setup_note).to include(
      "This file was generated by `rails generate rails_fields_kit:install`.",
      "Use it as a lightweight adoption checklist for wiring Rails Fields Kit into this host app and for recording app-specific notes.",
      "Keep maintained examples in the upstream docs; this generated file should point you to the next setup step, not become a second setup guide.",
      "## Suggested docs order",
      "Start with these while proving the first field:",
      "README first field quickstart: `README.md#first-field-quickstart`",
      "Setup guide RFK select lane: `doc/setup.md#rfk-select-setup-lane`",
      "Setup doctor status legend: `doc/setup.md#setup-doctor-status-legend`",
      "Use these after the first field works or when the host app hits that exact setup question:",
      "Setup doctor output review: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/setup_doctor_output_review.md>",
      "## Reference links",
      "Keep these links here for later lookup. They should stay compact; add app-specific notes above instead of turning this generated file into a full docs inventory.",
      "Upstream setup guide: https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/setup.md",
      "Upstream README: https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/README.md"
    )

    expect(generated_setup_note).not_to include(
      "## Maintained docs to read first",
      "## Remote endpoints and richer selects",
      "## Migration and helper selection",
      "## Release verification and visual review"
    )
  end

  it "keeps the generated setup checklist focused on the first host-app field before follow-up lanes" do
    expect(generated_setup_note).to include(
      "## Start here",
      "Finish this first pass before adding remote endpoints, release evidence, or visual review tasks.",
      "Table metadata work belongs after the first field works.",
      "The goal is to prove one server-rendered field in this host app and record any app-specific ownership notes.",
      "### First field route",
      "Complete these checks in order. Stop after the first field renders, record what worked, and use the later sections only when the host app needs that follow-up.",
      "- [ ] Confirm `config/initializers/rails_fields_kit.rb` matches this app's needs.",
      "- [ ] Install Tom Select with the JavaScript toolchain already used by this app.",
      "- [ ] Register `rails-fields-kit--tom-select` on the app's existing Stimulus application.",
      "- [ ] Load `tom-select/dist/css/tom-select.css` from the app's stylesheet or bundler entrypoint.",
      "- [ ] Follow the README first field quickstart or the setup guide `rfk_select` lane before adding remote endpoints.",
      "- [ ] Render one Rails Fields Kit field on a server-rendered form and record the field name below.",
      "### First-pass evidence",
      "- [ ] Run `rails rails_fields_kit:doctor` after the first-pass wiring to review detectable setup state, importmap pin target diagnostics, representative Stimulus registration advisory state, and manual checklist items.",
      "- [ ] Read the setup doctor status legend before triage: fix `[MISSING]` lines first, then treat `[MANUAL]` lines as host-app JavaScript toolchain checks.",
      "- [ ] Record the first Rails Fields Kit field and any app-specific ownership notes below.",
      "### Use only when the first pass needs it",
      "- [ ] If `rails_fields_kit` or `rails_fields_kit/tom_select_controller` cannot be resolved, use the upstream setup guide's unresolved imports troubleshooting section before changing aliases, importmap pins, Stimulus registration, Tom Select package setup, or CSS imports.",
      "- [ ] When the first pass needs richer select behavior, use the maintained docs for `selected_url:`, `option_description_field:`, `option_badge_field:`, `rfk_search_with`, `rfk_find_with`, and `rfk_create_with` instead of copying that setup here.",
      "## App-specific notes",
      "- First Rails Fields Kit field rendered:",
      "- JavaScript entrypoint used for Stimulus registration:",
      "- Stylesheet or bundler entrypoint used for Tom Select CSS:",
      "- Setup doctor command/output location:",
      "- Host-app owner for follow-up setup decisions:"
    )
  end
end
