# frozen_string_literal: true

require "rubygems"
require "spec_helper"

RSpec.describe "package contents" do
  let(:gemspec_path) { File.expand_path("../rails_fields_kit.gemspec", __dir__) }
  let(:specification) { Gem::Specification.load(gemspec_path) }
  let(:repo_agents_path) { File.expand_path("../AGENTS.md", __dir__) }
  let(:repo_agents) { File.read(repo_agents_path) }
  let(:product_profile_path) { File.expand_path("../Product Profile.md", __dir__) }
  let(:product_profile) { File.read(product_profile_path) }
  let(:generated_setup_note_path) do
    File.expand_path("../lib/generators/rails_fields_kit/templates/rails_fields_kit_setup.md", __dir__)
  end
  let(:generated_setup_note) { File.read(generated_setup_note_path) }

  it "ships the documented JavaScript package entrypoints" do
    expect(specification.files).to include(
      "package.json",
      "app/javascript/rails_fields_kit/index.js",
      "app/javascript/rails_fields_kit/tom_select_controller.js"
    )
  end

  it "ships the install-flow docs and generator artifacts described by README and setup" do
    expect(specification.files).to include(
      "README.md",
      "doc/setup.md",
      "doc/sample_app_checklist.md",
      "lib/generators/rails_fields_kit/install_generator.rb",
      "lib/generators/rails_fields_kit/templates/rails_fields_kit_setup.md"
    )
  end

  it "keeps the generated setup note pointed at the maintained walkthrough and public references" do
    expect(generated_setup_note).to include(
      "This file was generated by `rails generate rails_fields_kit:install`.",
      "Use it as a short checklist for wiring Rails Fields Kit into this host app and for recording app-specific notes.",
      "For the maintained walkthrough and copyable examples, use the upstream docs:",
      "Setup guide: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/setup.md>",
      "README: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/README.md>",
      "Public API: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/public_api.md>",
      "Configuration: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/configuration.md>",
      "Field helper reference: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/field_helpers.md>",
      "Controller helper reference: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/controller_helpers.md>",
      "Practical `rfk_select` migration guide: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/select_migration.md>",
      "Visual reference: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/tom_select_visual_reference.html>",
      "Events: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/events.md>",
      "Token suggestions: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/token_suggestions.md>",
      "Ransack suggestions: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/ransack_suggestions.md>",
      "Table adapter metadata: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/table_adapters.md>",
      "For a representative edit-form lane that uses `selected_url:` or `error_surface: true`, start with the setup guide and then review the events reference for `selected-load`, `selected-load-error`, and `detail.surface`."
    )
  end

  it "keeps the generated setup checklist aligned with the documented host-app setup lanes" do
    expect(generated_setup_note).to include(
      "## Setup checklist",
      "- [ ] Confirm `config/initializers/rails_fields_kit.rb` matches this app's needs.",
      "- [ ] Review `doc/configuration.md` before changing initializer defaults or text overrides.",
      "- [ ] Install Tom Select with the JavaScript toolchain already used by this app.",
      "- [ ] Register `rails-fields-kit--tom-select` on the app's existing Stimulus application.",
      "- [ ] If this app uses Vite or another bundler, add resolver or alias entries for `rails_fields_kit` and `rails_fields_kit/tom_select_controller`.",
      "- [ ] If this app uses importmap, add manual pins for `rails_fields_kit` and `rails_fields_kit/tom_select_controller` in `config/importmap.rb`.",
      "- [ ] Load `tom-select/dist/css/tom-select.css` from the app's stylesheet or bundler entrypoint.",
      "- [ ] Add the first `rfk_combobox` field and matching `rfk_search_with` / `rfk_find_with` / `rfk_create_with` endpoints.",
      "- [ ] Use `doc/controller_helpers.md` for the maintained endpoint option reference, including custom `action:` names.",
      "- [ ] If this app is replacing a server-rendered `collection_select`, review the practical `rfk_select` migration guide before adding extra reinitializers or controller glue.",
      "- [ ] Use `doc/field_helpers.md` when choosing between `rfk_select`, `rfk_grouped_select`, `rfk_enum_select`, `rfk_combobox`, `rfk_autocomplete`, `rfk_token_search`, `rfk_tags`, and `rfk_multi_select`.",
      "- [ ] Use `doc/tom_select_visual_reference.html` when this app needs a quick visual comparison of representative Tom Select-backed states.",
      "- [ ] Review remote option settings such as `selected_url:`, `option_description_field:`, and `option_badge_field:` in the public API guide before wiring richer selects.",
      "- [ ] If this app uses `selected_url:` or `error_surface: true`, review `doc/setup.md` for the representative edit-form wiring and `doc/events.md` for `selected-load`, `selected-load-error`, and `detail.surface`.",
      "- [ ] If this app uses `rfk_token_search`, review `doc/token_suggestions.md` for suggestion endpoint basics and `doc/ransack_suggestions.md` when those suggestions should map to Ransack metadata.",
      "- [ ] If this app renders table filters or cell editors from metadata, review `doc/table_adapters.md` before wiring `rfk_table_filters` or `rfk_table_cell_editors`.",
      "## App-specific notes",
      "- Stimulus entrypoint:",
      "- JavaScript resolver or alias location:",
      "- CSS entrypoint:",
      "- First field using Rails Fields Kit:",
      "- Follow-up tasks:"
    )
  end

  it "keeps the root maintainer docs aligned with the maintained docs inventory" do
    expect(repo_agents).to include(
      "- `lib/generators/rails_fields_kit/templates/rails_fields_kit_setup.md`: generated host-app setup note",
      "- `doc/tom_select_visual_reference.html`: static visual reference for representative Tom Select-backed states",
      "sync `README.md`, `doc/setup.md`, `lib/generators/rails_fields_kit/templates/rails_fields_kit_setup.md`, and root inventory docs such as `Product Profile.md`",
      "sync `README.md`, `doc/field_helpers.md`, and `doc/tom_select_visual_reference.html` together."
    )

    expect(product_profile).to include(
      "- `README.md`: public entrypoint and maintained docs map",
      "- `lib/generators/rails_fields_kit/templates/rails_fields_kit_setup.md`: generated host-app checklist that should stay pointed back to the maintained docs",
      "- `doc/tom_select_visual_reference.html`: static visual reference for representative Tom Select-backed states"
    )
  end

  it "ships the maintained public reference docs linked from README and setup" do
    expect(specification.files).to include(
      "doc/public_api.md",
      "doc/select_migration.md",
      "doc/field_helpers.md",
      "doc/controller_helpers.md",
      "doc/configuration.md",
      "doc/events.md",
      "doc/token_suggestions.md",
      "doc/ransack_suggestions.md",
      "doc/table_adapters.md",
      "doc/tom_select_visual_reference.html"
    )
  end

  it "ships the release-facing verification docs linked from README" do
    expect(specification.files).to include(
      "doc/development.md",
      "doc/sample_app_results.md",
      "doc/final_release_checklist.md",
      "doc/release.md",
      "doc/release_notes_0_1_1.md",
      "doc/release_notes_0_1_0.md"
    )
  end
end
