# frozen_string_literal: true

require "rubygems"
require "spec_helper"

RSpec.describe "package contents" do
  let(:gemspec_path) { File.expand_path("../rails_fields_kit.gemspec", __dir__) }
  let(:specification) { Gem::Specification.load(gemspec_path) }
  let(:readme_path) { File.expand_path("../README.md", __dir__) }
  let(:readme) { File.read(readme_path) }
  let(:repo_agents_path) { File.expand_path("../AGENTS.md", __dir__) }
  let(:repo_agents) { File.read(repo_agents_path) }
  let(:product_profile_path) { File.expand_path("../Product Profile.md", __dir__) }
  let(:product_profile) { File.read(product_profile_path) }
  let(:setup_doc_path) { File.expand_path("../doc/setup.md", __dir__) }
  let(:setup_doc) { File.read(setup_doc_path) }
  let(:visual_references_path) { File.expand_path("../doc/visual_references.md", __dir__) }
  let(:visual_references) { File.read(visual_references_path) }
  let(:public_api_path) { File.expand_path("../doc/public_api.md", __dir__) }
  let(:public_api) { File.read(public_api_path) }
  let(:field_helpers_path) { File.expand_path("../doc/field_helpers.md", __dir__) }
  let(:field_helpers) { File.read(field_helpers_path) }
  let(:form_builder_path) { File.expand_path("../lib/rails_fields_kit/form_builder.rb", __dir__) }
  let(:form_builder_source) { File.read(form_builder_path) }
  let(:generated_setup_note_path) do
    File.expand_path("../lib/generators/rails_fields_kit/templates/rails_fields_kit_setup.md", __dir__)
  end
  let(:generated_setup_note) { File.read(generated_setup_note_path) }

  it "ships the documented JavaScript package entrypoints" do
    expect(specification.files).to include(
      "package.json",
      "app/javascript/rails_fields_kit/index.js",
      "app/javascript/rails_fields_kit/tom_select_controller.js"
    )
  end

  it "ships the install-flow docs and generator artifacts described by README and setup" do
    expect(specification.files).to include(
      "README.md",
      "doc/setup.md",
      "doc/sample_app_checklist.md",
      "lib/generators/rails_fields_kit/install_generator.rb",
      "lib/generators/rails_fields_kit/templates/rails_fields_kit_setup.md"
    )
  end

  it "keeps the generated setup note pointed at the maintained walkthrough and public references" do
    expect(generated_setup_note).to include(
      "This file was generated by `rails generate rails_fields_kit:install`.",
      "Use it as a lightweight adoption checklist for wiring Rails Fields Kit into this host app and for recording app-specific notes.",
      "Keep maintained examples in the upstream docs; this generated file should point you to the next setup step, not become a second setup guide.",
      "## Maintained docs to read first",
      "These upstream docs remain the source of truth for copyable examples, public API details, and release checks.",
      "README: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/README.md>",
      "Setup guide: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/setup.md>",
      "Public API: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/public_api.md>",
      "Configuration: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/configuration.md>",
      "Field helper reference: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/field_helpers.md>",
      "Controller helper reference: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/controller_helpers.md>",
      "## Reference links",
      "Practical `rfk_select` migration guide: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/select_migration.md>",
      "Visual reference family: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/visual_references.md>",
      "Tom Select visual reference: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/tom_select_visual_reference.html>",
      "Selected preload release gate: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/selected_preload_release_gate.md>",
      "Events: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/events.md>",
      "Token suggestions: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/token_suggestions.md>",
      "Ransack suggestions: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/ransack_suggestions.md>",
      "Table adapter metadata: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/table_adapters.md>",
      "For a representative edit-form lane that uses `selected_url:` or `error_surface: true`, start with the setup guide and then review the events reference for `selected-load`, `selected-load-error`, and `detail.surface`."
    )
  end

  it "keeps the generated setup checklist aligned with the documented host-app setup lanes" do
    expect(generated_setup_note).to include(
      "## Start here",
      "Use this first pass to prove one server-rendered field before adding remote endpoints or richer Tom Select behavior.",
      "- [ ] Confirm `config/initializers/rails_fields_kit.rb` matches this app's needs.",
      "- [ ] Install Tom Select with the JavaScript toolchain already used by this app.",
      "- [ ] Register `rails-fields-kit--tom-select` on the app's existing Stimulus application.",
      "- [ ] Load `tom-select/dist/css/tom-select.css` from the app's stylesheet or bundler entrypoint.",
      "- [ ] Follow the README first field quickstart or the setup guide `rfk_select` lane before adding remote endpoints.",
      "- [ ] Record the first Rails Fields Kit field and any app-specific ownership notes below.",
      "## Remote endpoints and richer selects",
      "- [ ] Add the first `rfk_combobox` field and matching `rfk_search_with` / `rfk_find_with` / `rfk_create_with` endpoints.",
      "- [ ] Use `doc/controller_helpers.md` for the maintained endpoint option reference, including custom `action:` names.",
      "- [ ] Review remote option settings such as `selected_url:`, `option_description_field:`, and `option_badge_field:` in the public API guide before wiring richer selects.",
      "- [ ] If this app uses `selected_url:` or `error_surface: true`, review `doc/setup.md` for the representative edit-form wiring and `doc/events.md` for `selected-load`, `selected-load-error`, and `detail.surface`.",
      "- [ ] If this app uses importmap, run `rails generate rails_fields_kit:install --importmap` when `config/importmap.rb` exists, or add manual pins for `rails_fields_kit` and `rails_fields_kit/tom_select_controller`.",
      "- [ ] If this app uses Vite or another bundler, add resolver or alias entries for `rails_fields_kit` and `rails_fields_kit/tom_select_controller`.",
      "## Migration and helper selection",
      "- [ ] If this app is replacing a server-rendered `collection_select`, review the practical `rfk_select` migration guide before adding extra reinitializers or controller glue.",
      "- [ ] Use `doc/field_helpers.md` when choosing between `rfk_select`, `rfk_grouped_select`, `rfk_enum_select`, `rfk_combobox`, `rfk_autocomplete`, `rfk_token_search`, `rfk_tags`, and `rfk_multi_select`.",
      "- [ ] If this app uses `rfk_token_search`, review `doc/token_suggestions.md` for suggestion endpoint basics and `doc/ransack_suggestions.md` when those suggestions should map to Ransack metadata.",
      "- [ ] If this app renders table filters or cell editors from metadata, review `doc/table_adapters.md` before wiring `rfk_table_filters` or `rfk_table_cell_editors`.",
      "## Release verification and visual review",
      "- [ ] When host-app scripts import from `rails_fields_kit`, use `doc/public_api.md#javascript-exports` to confirm the current package-root exports and the rendered-field contract helper boundary.",
      "- [ ] If this app uses `selected_url:`, review `doc/selected_preload_release_gate.md` before release verification to confirm single and multiple selected preload request encoding expectations.",
      "- [ ] Use `doc/visual_references.md` as the maintained visual reference family index when this app needs quick comparisons of Tom Select-backed, text override, native helper, or table metadata states.",
      "- [ ] Use `doc/tom_select_visual_reference.html` when this app needs a quick visual comparison of representative Tom Select-backed states.",
      "## App-specific notes",
      "- Stimulus entrypoint:",
      "- JavaScript resolver or alias location:",
      "- CSS entrypoint:",
      "- First field using Rails Fields Kit:",
      "- Remote endpoint follow-up:",
      "- Release verification notes:",
      "- Follow-up tasks:"
    )
  end

  it "keeps README and setup JavaScript helper summaries pointed at the public API source of truth" do
    javascript_exports = markdown_section(public_api, "## JavaScript exports")

    expect(javascript_exports).to include(
      "### Current package-root exports",
      "`TomSelectController`",
      "rendered-field contract reader",
      "Future package-root helpers should follow the same boundary"
    )

    expect(readme).to include(
      "`rails_fields_kit/index.js` re-exports the same controller",
      "read-only rendered-field contract helpers",
      "use the JavaScript exports section in [`doc/public_api.md`](doc/public_api.md#javascript-exports) as the source of truth for the current helper list and responsibility boundary"
    )

    expect(setup_doc).to include(
      "The package root also exposes read-only rendered-field contract helpers",
      "Use [`public_api.md#javascript-exports`](public_api.md#javascript-exports) as the current source of truth for the helper list and return shape"
    )
  end

  it "keeps the root maintainer docs aligned with the maintained docs inventory" do
    expect(repo_agents).to include(
      "- `lib/generators/rails_fields_kit/templates/rails_fields_kit_setup.md`: generated host-app setup note",
      "- `doc/tom_select_visual_reference.html`: static visual reference for representative Tom Select-backed states",
      "- `doc/native_field_visual_reference.html`: static visual reference for representative native helper states",
      "sync `README.md`, `doc/setup.md`, `lib/generators/rails_fields_kit/templates/rails_fields_kit_setup.md`, and root inventory docs such as `Product Profile.md`",
      "sync `README.md`, `doc/field_helpers.md`, and any affected static visual reference together."
    )

    expect(product_profile).to include(
      "- `README.md`: public entrypoint and maintained docs map",
      "- `lib/generators/rails_fields_kit/templates/rails_fields_kit_setup.md`: generated host-app checklist that should stay pointed back to the maintained docs",
      "- `doc/visual_references.md`: maintained visual reference family map and scope notes",
      "- `doc/visual_reference_index.html`: one-screen reviewer entrypoint for the static visual reference family",
      "- `doc/tom_select_visual_reference.html` and `doc/native_field_visual_reference.html`: static visual references for representative Tom Select-backed and native helper states",
      "- `doc/tom_select_request_failure_visual_reference.html`: static visual reference for opt-in request-failure feedback and `error_surface: true` lanes"
    )
  end

  it "keeps the visual reference family map aligned with packaged static artifacts" do
    visual_reference_paths = [
      "doc/visual_reference_index.html",
      "doc/tom_select_visual_reference.html",
      "doc/tom_select_request_failure_visual_reference.html",
      "doc/tom_select_text_override_visual_reference.html",
      "doc/native_field_visual_reference.html",
      "doc/table_metadata_visual_reference.html",
      "doc/token_search_saved_search_visual_reference.html"
    ]

    expect(specification.files).to include("doc/visual_references.md", *visual_reference_paths)
    expect(product_profile).to include("- `doc/visual_references.md`: maintained visual reference family map and scope notes")

    visual_reference_paths.each do |path|
      link = path.delete_prefix("doc/")

      expect(product_profile).to include("`#{path}`")
      expect(visual_references).to include("[`#{link}`](#{link})")
    end
  end

  it "ships the maintained public reference docs linked from README and setup" do
    expect(specification.files).to include(
      "doc/public_api.md",
      "doc/select_migration.md",
      "doc/field_helpers.md",
      "doc/controller_helpers.md",
      "doc/configuration.md",
      "doc/events.md",
      "doc/token_suggestions.md",
      "doc/ransack_suggestions.md",
      "doc/table_adapters.md",
      "doc/tom_select_visual_reference.html",
      "doc/native_field_visual_reference.html",
      "doc/table_metadata_visual_reference.html"
    )
  end

  it "keeps native FormBuilder helpers aligned with public docs without making the quick chooser exhaustive" do
    native_helpers = native_helper_names_from(form_builder_source)
    native_section = public_api.match(/Native input helpers:\n\n(?<list>(?:- `rfk_[a-z_]+`\n)+)/)[:list]
    documented_native_helpers = native_section.scan(/`(rfk_[a-z_]+)`/).flatten
    quick_chooser = markdown_section(field_helpers, "## Quick chooser")

    expect(native_helpers).to eq(%w[
      rfk_text_field
      rfk_text_area
      rfk_number_field
      rfk_money_field
      rfk_percent_field
      rfk_email_field
      rfk_url_field
      rfk_phone_field
      rfk_search_field
    ])
    expect(documented_native_helpers).to eq(native_helpers)
    expect(quick_chooser).to include("the matching native helper such as")
  end

  it "ships the release-facing verification docs linked from README" do
    expect(specification.files).to include(
      "doc/development.md",
      "doc/sample_app_results.md",
      "doc/final_release_checklist.md",
      "doc/selected_preload_release_gate.md",
      "doc/release.md",
      "doc/release_notes_0_1_1.md",
      "doc/release_notes_0_1_0.md"
    )
  end

  def native_helper_names_from(source)
    source.scan(/^    def (rfk_[a-z_]+).*?\n(.*?)^    end/m).filter_map do |helper_name, body|
      helper_name if body.include?("rfk_native_field(")
    end
  end

  def markdown_section(document, heading)
    document.split(heading, 2).last.split(/\n(?=##?\s)/, 2).first
  end
end
