# frozen_string_literal: true

require "rubygems"
require "spec_helper"

RSpec.describe "package contents" do
  let(:gemspec_path) { File.expand_path("../rails_fields_kit.gemspec", __dir__) }
  let(:specification) { Gem::Specification.load(gemspec_path) }
  let(:generated_setup_note_path) do
    File.expand_path("../lib/generators/rails_fields_kit/templates/rails_fields_kit_setup.md", __dir__)
  end
  let(:generated_setup_note) { File.read(generated_setup_note_path) }

  it "ships the documented JavaScript package entrypoints" do
    expect(specification.files).to include(
      "package.json",
      "app/javascript/rails_fields_kit/index.js",
      "app/javascript/rails_fields_kit/tom_select_controller.js"
    )
  end

  it "ships the install-flow docs and generator artifacts described by README and setup" do
    expect(specification.files).to include(
      "README.md",
      "doc/setup.md",
      "doc/sample_app_checklist.md",
      "lib/generators/rails_fields_kit/install_generator.rb",
      "lib/generators/rails_fields_kit/templates/rails_fields_kit_setup.md"
    )
  end

  it "keeps the generated setup note pointed at the maintained walkthrough and public references" do
    expect(generated_setup_note).to include(
      "This file was generated by `rails generate rails_fields_kit:install`.",
      "Use it as a short checklist for wiring Rails Fields Kit into this host app and for recording app-specific notes.",
      "For the maintained walkthrough and copyable examples, use the upstream docs:",
      "Setup guide: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/setup.md>",
      "README: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/README.md>",
      "Public API: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/public_api.md>",
      "Configuration: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/configuration.md>",
      "Field helper reference: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/field_helpers.md>",
      "Controller helper reference: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/controller_helpers.md>",
      "Events: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/events.md>",
      "Token suggestions: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/token_suggestions.md>",
      "Ransack suggestions: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/ransack_suggestions.md>",
      "Table adapter metadata: <https://github.com/matsuo-haruhito/rails_fields_kit/blob/main/doc/table_adapters.md>"
    )
  end

  it "keeps the generated setup checklist aligned with the documented host-app setup lanes" do
    expect(generated_setup_note).to include(
      "## Setup checklist",
      "- [ ] Review `doc/configuration.md` before changing initializer defaults or text overrides.",
      "- [ ] Register `rails-fields-kit--tom-select` on the app's existing Stimulus application.",
      "- [ ] If this app uses Vite or another bundler, add resolver or alias entries for `rails_fields_kit` and `rails_fields_kit/tom_select_controller`.",
      "- [ ] If this app uses importmap, add manual pins for `rails_fields_kit` and `rails_fields_kit/tom_select_controller` in `config/importmap.rb`.",
      "- [ ] Use `doc/controller_helpers.md` for the maintained endpoint option reference, including custom `action:` names.",
      "- [ ] Use `doc/field_helpers.md` when choosing between `rfk_select`, `rfk_combobox`, `rfk_autocomplete`, `rfk_token_search`, `rfk_tags`, and `rfk_multi_select`.",
      "## App-specific notes",
      "- Stimulus entrypoint:",
      "- JavaScript resolver or alias location:",
      "- Follow-up tasks:"
    )
  end

  it "ships the maintained public reference docs linked from README and setup" do
    expect(specification.files).to include(
      "doc/public_api.md",
      "doc/select_migration.md",
      "doc/field_helpers.md",
      "doc/controller_helpers.md",
      "doc/configuration.md",
      "doc/events.md",
      "doc/token_suggestions.md",
      "doc/ransack_suggestions.md",
      "doc/table_adapters.md"
    )
  end

  it "ships the release-facing verification docs linked from README" do
    expect(specification.files).to include(
      "doc/development.md",
      "doc/sample_app_results.md",
      "doc/final_release_checklist.md",
      "doc/release.md",
      "doc/release_notes_0_1_1.md",
      "doc/release_notes_0_1_0.md"
    )
  end
end
